# -*- coding: utf-8 -*-
"""PRODIGY_GA_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V6S0uqmW55UOaq6FXosK88BO9Dtw1eNd
"""

!pip install transformers torch gradio

from transformers import GPT2LMHeadModel
from transformers import GPT2Tokenizer

import torch
import gradio as gr

tokenizer = GPT2Tokenizer.from_pretrained(
    "gpt2"
)

model = GPT2LMHeadModel.from_pretrained(
    "gpt2"
)

def generate_text(prompt):

    inputs = tokenizer.encode(
        prompt,
        return_tensors="pt"
    )

    outputs = model.generate(

        inputs,

        max_length=100,

        do_sample=True,

        temperature=0.8,

        top_k=50,

        top_p=0.95

    )

    generated_text = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    return generated_text

with gr.Blocks(
    theme=gr.themes.Soft(),
    title="GPT-2 Text Generator"
) as demo:

    gr.Markdown("""
    # 🤖 GPT-2 AI Text Generator

    Generate creative and context-aware text using GPT-2.

    ### Workflow
    ✍️ Prompt → 🧠 GPT-2 Model → 📜 Generated Text
    """)

    with gr.Row():

        with gr.Column():

            prompt_input = gr.Textbox(
                label="✍️ Enter Prompt",
                lines=6,
                placeholder="""
Examples:

Once upon a time

Artificial Intelligence is

In a magical forest

The future of technology
"""
            )

            generate_btn = gr.Button(
                "🚀 Generate Text",
                variant="primary"
            )

        with gr.Column():

            output_text = gr.Textbox(
                label="📜 Generated Text",
                lines=15
            )

    generate_btn.click(
        fn=generate_text,
        inputs=prompt_input,
        outputs=output_text
    )

    gr.Markdown("""
    ---
    ### Sample Prompts

    • Once upon a time

    • Artificial Intelligence is

    • The future of education

    • In a distant galaxy

    • Machine Learning can
    """)

demo.launch(share=True)

